FROM python:3.9
ADD Summer2021-Internships Summer2021-Internships
RUN ["apt-get","update"]
RUN ["pip","install","requests"]
RUN ["pip","install","beautifulsoup4"]
RUN ["pip","install","Markdown"]
RUN ["pip","install","gspreed"]
RUN ["pip","install","gs.dmarc"]
RUN ["pip","install","bs4"]
RUN ["apt-get","install","-y","python-pip"]
RUN ["pip","install","Flask"]
RUN ["pip","install","gspread"]
RUN ["pip","install","Django"]
RUN ["pip","install","markdown2"]
CMD python Summer2021-Internships/sync.py

