FROM python:3.9-buster
ADD weakfilescan weakfilescan
RUN ["pip","install","OpsletsEc2"]
RUN ["pip","install","requests"]
RUN ["pip","install","beautifulsoup4"]
RUN ["pip","install","om-package-fynd"]
RUN ["pip","install","labelImg"]
RUN ["pip","install","hyhyhy"]
RUN ["pip","install","bs4"]
RUN ["pip","install","lightbulb-framework"]
RUN ["pip","install","gdctools"]
RUN ["pip","install","controller"]
RUN ["pip","install","androidviewclient"]
RUN ["pip","install","config"]
RUN ["pip","install","common"]
CMD cd weakfilescan && python wyspider.py 133.133.133.47:8000

