FROM python:3.8
ADD stumpy stumpy
RUN ["pip","install","python-mpd2"]
RUN ["pip","install","requests"]
RUN ["pip","install","psycopg2"]
RUN ["pip","install","python-dateutil"]
RUN ["pip","install","pathlib"]
RUN ["pip","install","pytest"]
RUN ["pip","install","path.py"]
RUN ["pip","install","floss"]
RUN ["pip","install","aamp"]
RUN ["pip","install","stump"]
RUN ["pip","install","numpy"]
RUN ["pip","install","stumpy"]
RUN ["pip","install","chai"]
RUN ["pip","install","numba"]
RUN ["pip","install","chains"]
CMD cd stumpy && python test.py

