FROM python:3.9
ADD petastorm petastorm
RUN ["pip","install","di-py"]
RUN ["pip","install","pan-python"]
RUN ["pip","install","pandacan"]
RUN ["pip","install","future"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","pyparsing"]
RUN ["pip","install","appdirs"]
RUN ["pip","install","packaging"]
RUN ["pip","install","fut"]
RUN ["pip","install","petastorm"]
RUN ["pip","install","torch"]
RUN ["pip","install","cortexutils"]
RUN ["pip","install","gcsfs"]
RUN ["pip","install","pandas"]
RUN ["pip","install","s3fs"]
RUN ["pip","install","numpy"]
RUN ["pip","install","diskcache"]
RUN ["pip","install","pyarrow"]
CMD cd petastorm && python test.py

